No longer declare support for Python 3.6 (it was already not tested). @davisagli
